language: rust
cache: cargo

matrix:
  include:
    - rust: stable
      env: TARGET=i686-pc-windows-msvc
      os: windows
    - rust: stable
      env: TARGET=i686-unknown-linux-gnu
      os: linux
install: rustup target add ${TARGET}
script:
    - cargo build --verbose --target=${TARGET}
    - cargo test --verbose --target=${TARGET} -- --test-threads=1
branches:
  only:
    - master