language: rust
cache: cargo

matrix:
  include:
    - rust: stable
      env: TARGET=i686-pc-windows-msvc
      os: windows
    - rust: stable
      env: TARGET=i686-pc-linux-gnu
      os: linux
script:
    - cargo build --verbose
    - cargo test -- --test-threads=1
branches:
  only:
    - master