language: rust
cache: cargo

matrix:
  include:
    - rust: stable
      env: TOOLCHAIN=stable-i686-pc-windows-msvc
      os: windows
    - rust: stable
      env: TOOLCHAIN=stable-i686-unknown-linux-gnu
      os: linux
install: rustup default ${TOOLCHAIN}
script:
    - cargo build --verbose
    - cargo test -- --test-threads=1
branches:
  only:
    - master